version: '3.8'

services:
  # Service untuk aplikasi Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    image: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - db
      - redis

  # Service untuk web server (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80" # Akses aplikasi di localhost:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - app

  # Service untuk database MySQL
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

  # Service untuk Redis (optional, jika Laravel menggunakan Redis)
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
    driver: local
